baseURL = "/"
languageCode = "en-us"
title = "Indiana Legislative Tools"

[permalinks]
  issues = "/issues/:sections[1]/:sections[2]/:filename"

[params]
  description = "Track bills, budgets, and issues in the Indiana Legislature"
  apiEndpoint = "https://indianageneralassembly-production.up.railway.app"

[menu]
  [[menu.main]]
    name = "Bill Tracker"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Issues"
    url = "/issues/"
    weight = 2
  [[menu.main]]
    name = "Budget View"
    url = "/budget/"
    weight = 3